export const PERMISSIONS = {
  ADMIN: "admin",
  INSTITUICAO_ENSINO: "education_institute",
  CAMPO_ESTAGIO: "service",
};

export const ALL_PERMISSIONS = [
  PERMISSIONS.ADMIN,
  PERMISSIONS.INSTITUICAO_ENSINO,
  PERMISSIONS.CAMPO_ESTAGIO,
];

const MANAGEMENT_PERMISSIONS = [PERMISSIONS.ADMIN, PERMISSIONS.INSTITUICAO_ENSINO, PERMISSIONS.CAMPO_ESTAGIO];
export { MANAGEMENT_PERMISSIONS };
export default PERMISSIONS;
